using EnglishBots_V2.Enum;
using System.Collections.Generic;

namespace EnglishBots_V2.Structures
{
    public static class Statics
    {
        public static Dictionary<string, Words> WordToEnumDictionary = new Dictionary<string, Words>
    {
         {"бить", Words.Beat},
         {"beat", Words.Beat},
         {"пребывать",  Words.Abide},
         {"возникать",  Words.Arise},
         {"будить",  Words.Awake},
         {"быть",  Words.Be},
         {"носить",  Words.Bear},
         {"становиться",  Words.Become},
         {"случаться",  Words.Befall},
         {"начинать",  Words.Begin},
         {"вглядываться",  Words.Behold},
         {"гнуть",  Words.Bend},
         {"умолять",  Words.Beseech},
         {"окружать",  Words.Beset},
         {"держать пари",  Words.Bet},
         {"предлагать цену",  Words.Bid},
         {"связывать",  Words.Bind},
         {"кусать",  Words.Bite},
         {"кровоточить",  Words.Bleed},
         {"дуть",  Words.Blow},
         {"ломать",  Words.Break},
         {"порождать",  Words.Breed},
         {"приносить",  Words.Bring},
         {"вещать",  Words.Broadcast},
         {"строить",  Words.Build},
         {"гореть",  Words.Burn},
         {"взрывать",  Words.Burst},
         {"покупать",  Words.Buy},
         {"мочь физически",  Words.Can},
         {"бросать",  Words.Cast},
         {"ловить",  Words.Catch},
         {"выбирать",  Words.Choose},
         {"прилипать",  Words.Cling},
         {"рассечь",  Words.Cleave},
         {"одеть",  Words.Clothe},
         {"приходить",  Words.Come},
         {"оценивать",  Words.Cost},
         {"ползать",  Words.Creep},
         {"резать",  Words.Cut},
         {"сметь",  Words.Dare},
         {"иметь дело",  Words.Deal},
         {"копать",  Words.Dig},
         {"нырять",  Words.Dive},
         {"делать",  Words.Do},
         {"тащить",  Words.Draw},
         {"видеть сны",  Words.Dream},
         {"пить",  Words.Drink},
         {"ехать",  Words.Drive},
         {"обитать",  Words.Dwell},
         {"есть",  Words.Eat},
         {"падать",  Words.Fall},
         {"кормить",  Words.Feed},
         {"чувствовать",  Words.Feel},
         {"бороться",  Words.Fight},
         {"находить",  Words.Find},
         {"подходить",  Words.Fit},
         {"спасаться бегством",  Words.Flee},
                                                                            //{"Кидать",  Words.Fling},
         {"летать",  Words.Fly},
         {"запрещать",  Words.Forbid},
         {"предвидеть",  Words.Forecast},
         {"забывать",  Words.Forget},
         {"отказываться",  Words.Forego},
         {"предсказывать",  Words.Foretell},
         {"прощать",  Words.Forgive},
                                                                            //{"Отказываться",  Words.Forsake},
         {"замерзать",  Words.Freeze},
         {"получать",  Words.Get},
         {"позолотить",  Words.Gild},
         {"давать",  Words.Give},
         {"идти",  Words.Go},
         {"точить",  Words.Grind},
         {"расти",  Words.Grow},
         {"висеть",  Words.Hang},
         {"иметь",  Words.Have},
         {"рубить",  Words.Hew},
         {"слышать",  Words.Hear},
         {"прятать",  Words.Hide},
         {"ударять",  Words.Hit},
         {"владеть",  Words.Hold},
         {"повредить",  Words.Hurt},
         {"держать",  Words.Keep},
         {"становиться на Колени",  Words.Kneel},
         {"вязать",  Words.Knit},
         {"знать",  Words.Know},
         {"класть",  Words.Lay},
         {"вести",  Words.Lead},
         {"опираться",  Words.Lean},
         {"прыгать",  Words.Leap},
         {"учиться",  Words.Learn},
         {"уезжать",  Words.Leave},
         {"одалживать",  Words.Lend},
         {"позволять",  Words.Let},
         {"лежать",  Words.Lie},
         {"зажигать",  Words.Light},
         {"терять",  Words.Lose},
         {"заставлять",  Words.Make},
         {"мочь",  Words.May},
         {"значить",  Words.Mean},
         {"встречать",  Words.Meet},
         {"ослышаться",  Words.Mishear},
         {"класть не на место",  Words.Mislay},
         {"ошибаться",  Words.Mistake},
         {"косить",  Words.Mow},
         {"догнать",  Words.Overtake},
         {"платить",  Words.Pay},
         {"доказывать",  Words.Prove},
         {"ложить",  Words.Put},
         {"оставлять",  Words.Quit},
         {"читать",  Words.Read},
         {"перестраивать",  Words.Rebuild},
         {"освобождать",  Words.Rid},
         {"ехать верхом",  Words.Ride},
         {"звонить",  Words.Ring},
         {"подниматься",  Words.Rise},
         {"бежать",  Words.Run},
         {"пилить",  Words.Saw},
         {"сказать",  Words.Say},
         {"видеть",  Words.See},
         {"искать",  Words.Seek},
         {"продавать",  Words.Sell},
         {"посылать",  Words.Send},
         {"помещать",  Words.Set},
         {"шить",  Words.Sew},
         {"трясти",  Words.Shake},
         {"быть должным",  Words.Shall},
         {"брить",  Words.Shave},
         {"стричь",  Words.Shear},
         {"сбрасывать",  Words.Shed},
         {"сиять",  Words.Shine},
         {"обувать",  Words.Shoe},
         {"стрелять",  Words.Shoot},
         {"показывать",  Words.Show},
         {"сокращаться",  Words.Shrink},
         {"закрывать",  Words.Shut},
         {"петь",  Words.Sing},
         {"опускаться",  Words.Sink},
         {"сидеть",  Words.Sit},
         {"убивать",  Words.Slay},
         {"спать",  Words.Sleep},
         {"скользить",  Words.Slide},
         {"швырять",  Words.Sling},
         {"резать В Длину",  Words.Slit},
         {"пахнуть",  Words.Smell},
         {"сеять",  Words.Sow},
         {"говорить",  Words.Speak},
         {"спешить",  Words.Speed},
         {"произносить слово по буквам",  Words.Spell},
         {"тратить",  Words.Spend},
         {"проливать",  Words.Spill},
         {"прясть",  Words.Spin},
         {"плевать",  Words.Spit},
         {"раскалывать",  Words.Split},
         {"портить",  Words.Spoil},
         {"распространяться",  Words.Spread},
         {"вскочить",  Words.Spring},
         {"стоять",  Words.Stand},
         {"воровать",  Words.Steal},
         {"втыкать",  Words.Stick},
         {"жалить",  Words.Sting},
         {"вонять",  Words.Stink},
         {"усеять",  Words.Strew},
         {"шагать",  Words.Stride},
         {"поражать",  Words.Strike},
         {"натягивать",  Words.String},
         {"стремиться",  Words.Strive},
         {"клясться",  Words.Swear},
         {"мести",  Words.Sweep},
         {"пухнуть",  Words.Swell},
         {"плавать",  Words.Swim},
         {"качать",  Words.Swing},
         {"брать",  Words.Take},
         {"обучать",  Words.Teach},
         {"рвать",  Words.Tear},
         {"рассказывать",  Words.Tell},
         {"думать",  Words.Think},
         {"кидать",  Words.Throw},
         {"толкать",  Words.Thrust},
         {"ступать",  Words.Tread},
         {"разгибаться",  Words.Unbend},
         {"испытывать",  Words.Undergo},
         {"понимать",  Words.Understand},
         {"предпринимать",  Words.Undertake},
         {"опрокидывать",  Words.Upset},
         {"просыпаться",  Words.Wake},
         {"носить вещи",  Words.Wear},
         {"ткать",  Words.Weave},
         {"венчать",  Words.Wed},
         {"плакать",  Words.Weep},
         {"хотеть быть",  Words.Will},
         {"мочить",  Words.Wet},
         {"выигрывать",  Words.Win},
         {"заводить",  Words.Wind}, //механизм
         {"брать назад",  Words.Withdraw},
         {"жать",  Words.Wring},
         {"писать",  Words.Write},
                                                                  };

        public static Dictionary<Words, Word> EnumToObjectDictionary = new Dictionary<Words, Word>
            {
             {
                   Words.Beat, new Word
                   {
                    RussianName = "Бить",
                    FirstForm = "beat",
                    SecondForm = "beat",
                    ThirdForm = "beaten",
                    SentencesWithWordList = new List<string>
                    {
                    "📌Beat eggs",
                    "Бить яйца",
                    "___________________________________________",
                    "📌He beat me at chess",
                    "Он бил меня в шахматы",
                    "___________________________________________",
                    "📌I've seen girls who were beaten by their mothers and brothers and fathers and uncles",
                    "Я видел девушек, которых избивали их матери, братья, отцы и дяди."
                    },
              }
             },
             {
                Words.Abide, new Word
                {
                   RussianName = "Пребывать",
                   FirstForm = "abide",
                   SecondForm = "abode",
                   ThirdForm = "abode",
                   SentencesWithWordList = new List<string>
                   {
                       "📌I can't abide that man",
                       "📍Я не могу терпеть этого человека",
                       "___________________________________________",
                       "📌The king went to visit his daughter and abode at her palace for ten days",
                       "📍Царь отправился в гости к своей дочери и оставался в ее дворце в течение десяти дней.",
                       "___________________________________________",
                       "📌He had abode there till mid-day",
                       "📍Он жил там до полудня"
                   }
                }
             },
            {
                Words.Arise, new Word
                {
                    RussianName=    "Возникать",
                    FirstForm=  "arise",
                    SecondForm= "arose",
                    ThirdForm=  "arisen",
                    SentencesWithWordList = new List<string>
                    {   "📌Another difficulty may arise from unregulated conflict",
                        "📌Другая проблема может возникнуть из-за нерегулируемого конфликта",
                        "___________________________________________",
                        "📌A shout arose from the crowd",
                        "📌Из толпы раздался крик",
                        "___________________________________________",
                        "📌A big problem has arisen",
                        "📌Возникла большая проблема"
                    }
                }
            },
            {
                Words.Awake, new Word
                {
                    RussianName=    "Будить",
                    FirstForm=  "awake",
                    SecondForm= "awoke",
                    ThirdForm=  "awoken",
                    SentencesWithWordList =new List<string>
                    {
                        "📌I will awake you",
                        "📌Я тебя разбужу",
                        "___________________________________________",
                        "📌He awoke in his surroundings",
                        "📌Он проснулся в своем окружении",
                        "___________________________________________",
                        "📌He has awoken after 300 years",
                        "📌Он проснулся через 300 лет"
                    }
                }
            },
            {
                Words.Be, new Word
                {   RussianName=    "Быть",
                    FirstForm=  "be",
                    SecondForm= "was",
                    ThirdForm=  "been",
                    SentencesWithWordList =new List<string>
                    {
                        "📌Do as you would be done by? ",
                        "📌Делай, как ты бы сделал?",
                        "___________________________________________",
                        "📌I wish you were here. ",
                        "📌Как бы мне хотелось, чтобы ты был здесь.",
                        "___________________________________________",
                        "📌Have you ever been to Spain?",
                        "📌Вы когда-нибудь были в Испании?"
                    }
                }
            },
            {   Words.Bear, new Word
            {   RussianName=    "Носить",
                FirstForm=  "bear",
                SecondForm= "bore",
                ThirdForm=  "born",
                SentencesWithWordList =new List<string>
                {
                    "📌My shares bear 10% interest",
                    "📌Мои акции приносят 10%",
                    "___________________________________________",
                    "📌He bore the name 'Shaun'",
                    "📌Он носил имя «Шон»",
                    "___________________________________________",
                    "📌Jane was born in March",
                    "📌Джейн родилась в марте"
                }
            }
            },
            {   Words.Become, new Word
            {   RussianName= "Становиться",
                FirstForm=  "become",
                SecondForm= "became",
                ThirdForm=  "become",
                SentencesWithWordList =new List<string>
                {
                    "📌The dress becomes you ",
                    "📌2222",
                    "___________________________________________",
                    "📌His grandparents became older. ",
                    "📌2222",
                    "___________________________________________",
                    "📌It has become a very big problem",
                    "📌2222"
                }
            }
            },
            {   Words.Befall, new Word
            {   RussianName=  "Случаться",
                FirstForm=  "befall",
                SecondForm= "befell",
                ThirdForm=  "befallen",
                SentencesWithWordList =new List<string>
                {
                    "📌1111",
                     "📌2222",
                     "___________________________________________",
                     "📌1111",
                     "📌2222",
                     "___________________________________________",
                     "📌1111",
                     "📌2222"
                }
            }
            },
            {   Words.Begin, new Word
            {
                RussianName=    "Начинать",
                FirstForm=  "begin",
                SecondForm= "began",
                ThirdForm=  "begun",
                SentencesWithWordList =new List<string>
                {
                    "📌1111",
                     "📌2222",
                     "___________________________________________",
                     "📌1111",
                     "📌2222",
                     "___________________________________________",
                     "📌1111",
                     "📌2222"
                }
            }
            },
            {   Words.Behold, new Word
            {   RussianName=    "Вглядываться",
                FirstForm=  "behold",
                SecondForm= "beheld",
                ThirdForm=  "beheld",
                SentencesWithWordList =new List<string>
                {
                    "📌1111",
                     "📌2222",
                     "___________________________________________",
                     "📌1111",
                     "📌2222",
                     "___________________________________________",
                     "📌1111",
                     "📌2222"
                }
            }
            },
            {
                Words.Bend, new Word
                {
                    RussianName= "Гнуть",
                    FirstForm=   "bend",
                    SecondForm=  "bent",
                    ThirdForm=   "bent",
                    SentencesWithWordList =new List<string>
                    {
                        "📌they want to bend me to their will",
                        "📌они хотят подчинить меня своей воле",
                        "___________________________________________",
                        "📌he bent his great finger",
                        "📌он согнул большой палец",
                        "___________________________________________",
                        "📌he bent down slightly",
                        "📌он слегка наклонился"
                    }
                }
            },
            {   Words.Beseech , new Word   {   RussianName=    "Умолять",  FirstForm=  "beseech",  SecondForm= "besought",  ThirdForm=  "besought",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Beset,new Word   {   RussianName=    "Окружать",  FirstForm=  "beset",  SecondForm= "beset",  ThirdForm=  "beset",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Bet , new Word   {   RussianName=    "Держать Пари",  FirstForm=  "bet",  SecondForm= "bet",  ThirdForm=  "bet",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Bid , new Word   {   RussianName=    "Предлагать Цену",  FirstForm=  "bid",  SecondForm= "bid",  ThirdForm=  "bid",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Bind, new Word   {   RussianName=    "Связывать",  FirstForm=  "bind",  SecondForm= "bound",  ThirdForm=  "bound",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Bite, new Word   {   RussianName=    "Кусать",  FirstForm=  "bite",  SecondForm= "bit",  ThirdForm=  "bitten",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Bleed,new Word   {   RussianName=    "Кровоточить",  FirstForm=  "bleed",  SecondForm= "bled",  ThirdForm=  "bled",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Blow, new Word   {   RussianName=    "Дуть",  FirstForm=  "blow",  SecondForm= "blew",  ThirdForm=  "blown",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Break,new Word   {   RussianName=    "Ломать",  FirstForm=  "break",  SecondForm= "broke",  ThirdForm=  "broken",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Breed,new Word   {   RussianName=    "Порождать",  FirstForm=  "breed",  SecondForm= "bred",  ThirdForm=  "bred",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {
                Words.Bring,new Word
                {
                    RussianName=    "Приносить",
                    FirstForm=  "bring",
                    SecondForm= "brought",
                    ThirdForm=  "brought",
                    SentencesWithWordList =new List<string>
                    {
                         "📌Did you bring her flowers? ",
                         "📌Ты принес ей цветы?",
                         "___________________________________________",
                         "📌I brought you two paintings. ",
                         "📌Я принес тебе две картины.",
                         "___________________________________________",
                         "📌For all the suffering he brought her...",
                         "📌За все страдания, которые он принес ей ..."
                    }
                }
            },
         {   Words.Broadcast,new Word   {   RussianName=    "Вещать",  FirstForm=  "broadcast",  SecondForm= "broadcast",  ThirdForm=  "broadcast",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {
                Words.Build,new Word
                 {   RussianName=    "Строить",
                     FirstForm=  "build",
                     SecondForm= "built",
                     ThirdForm=  "built",
                     SentencesWithWordList =new List<string>
                     {
                             "📌Helping 'em build a road. ",
                             "📌Помочь им построить дорогу.",
                             "___________________________________________",
                             "📌You want to get the center built? ",
                             "📌Вы хотите построить центр?",
                             "___________________________________________",
                             "📌Rome wasn't built in a day.",
                             "📌Рим не был построен за один день."
                     }
                 }
         },
         {
                Words.Burn, new Word
                {
                    RussianName=    "Гореть",
                    FirstForm=  "burn",
                    SecondForm= "burnt",
                    ThirdForm=  "burnt",
                    SentencesWithWordList =new List<string>
                    {
                    "📌It burns all night. ",
                     "📌Горит всю ночь.",
                     "___________________________________________",
                     "📌You burnt all bridges with me when last we met. ",
                     "📌Вы сожгли все мосты со мной, когда мы в последний раз встречались.",
                     "___________________________________________",
                     "📌 I burnt the toast.",
                     "📌Я сжег тост."
                    }
                }
        },
         {
                Words.Burst,new Word
                {
                    RussianName= "Взрывать",
                    FirstForm=  "burst",
                    SecondForm= "burst",
                    ThirdForm=  "burst",
                    SentencesWithWordList =new List<string>
                    {
                     "📌He's about to burst.",
                     "📌Он собирается взорваться.",
                     "___________________________________________",
                     "📌My head is gonna burst!",
                     "📌Моя голова лопнет!",
                     "___________________________________________",
                     "📌this house bursting at the seams",
                     "📌этот дом трещит по швам"
                    }
                }
         },
         {   Words.Buy , new Word   {   RussianName=    "Покупать",  FirstForm=  "buy",  SecondForm= "bought",  ThirdForm=  "bought",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Can , new Word   {   RussianName=    "Мочь Физически",  FirstForm=  "can",  SecondForm= "could",  ThirdForm=  "could",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Cast, new Word   {   RussianName=    "Бросать",  FirstForm=  "cast",  SecondForm= "cast",  ThirdForm=  "cast",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Catch,new Word   {   RussianName=    "Ловить",  FirstForm=  "catch",  SecondForm= "caught",  ThirdForm=  "caught",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Choose, new Word   {   RussianName=    "Выбирать",  FirstForm=  "choose",  SecondForm= "chose",  ThirdForm=  "chosen",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Cling,new Word   {   RussianName=    "Прилипать",  FirstForm=  "cling",  SecondForm= "clung",  ThirdForm=  "clung",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Cleave, new Word   {   RussianName=    "Рассечь",  FirstForm=  "cleave",  SecondForm= "cleft",  ThirdForm=  "cloven",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Clothe, new Word   {   RussianName=    "Одеть",  FirstForm=  "clothe",  SecondForm= "clothed",  ThirdForm=  "clothed",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Come, new Word   {   RussianName=    "Приходить",  FirstForm=  "come",  SecondForm= "came",  ThirdForm=  "come",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Cost, new Word   {   RussianName=    "Оценивать",  FirstForm=  "cost",  SecondForm= "cost",  ThirdForm=  "cost",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Creep,new Word   {   RussianName=    "Ползать",  FirstForm=  "creep",  SecondForm= "crept",  ThirdForm=  "crept",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Cut , new Word   {   RussianName=    "Резать",  FirstForm=  "cut",  SecondForm= "cut",  ThirdForm=  "cut",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Dare, new Word   {   RussianName=    "Сметь",  FirstForm=  "dare",  SecondForm= "durst",  ThirdForm=  "dared",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Deal, new Word   {   RussianName=    "Иметь Дело",  FirstForm=  "deal",  SecondForm= "dealt",  ThirdForm=  "dealt",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Dig , new Word   {   RussianName=    "Копать",  FirstForm=  "dig",  SecondForm= "dug",  ThirdForm=  "dug",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Dive, new Word   {   RussianName=    "Нырять",  FirstForm=  "dive",  SecondForm= "dove",  ThirdForm=  "dived",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Do , new Word   {   RussianName=    "Делать",  FirstForm=  "do/does",  SecondForm= "did",  ThirdForm=  "done",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Draw, new Word   {   RussianName=    "Тащить",  FirstForm=  "draw",  SecondForm= "drew",  ThirdForm=  "drawn",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Dream,new Word   {   RussianName=    "Видеть Сны",  FirstForm=  "dream",  SecondForm= "dreamt",  ThirdForm=  "dreamt",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Drink,new Word   {   RussianName=    "Пить",  FirstForm=  "drink",  SecondForm= "drank",  ThirdForm=  "drunk",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Drive,new Word   {   RussianName=    "Ехать",  FirstForm=  "drive",  SecondForm= "drove",  ThirdForm=  "driven",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Dwell,new Word   {   RussianName=    "Обитать",  FirstForm=  "dwell",  SecondForm= "dwelt",  ThirdForm=  "dwelt",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Eat , new Word   {   RussianName=    "Есть",  FirstForm=  "eat",  SecondForm= "ate",  ThirdForm=  "eaten",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Fall, new Word   {   RussianName=    "Падать",  FirstForm=  "fall",  SecondForm= "fell",  ThirdForm=  "fallen",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Feed, new Word   {   RussianName=    "Кормить",  FirstForm=  "feed",  SecondForm= "fed",  ThirdForm=  "fed",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Feel, new Word   {   RussianName=    "Чувствовать",  FirstForm=  "feel",  SecondForm= "felt",  ThirdForm=  "felt",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Fight,new Word   {   RussianName=    "Бороться",  FirstForm=  "fight",  SecondForm= "fought",  ThirdForm=  "fought",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Find, new Word   {   RussianName=    "Находить",  FirstForm=  "find",  SecondForm= "found",  ThirdForm=  "found",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Fit , new Word   {   RussianName=    "Подходить",  FirstForm=  "fit",  SecondForm= "fit",  ThirdForm=  "fit",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Flee, new Word   {   RussianName=    "Бежать",  FirstForm=  "flee",  SecondForm= "fled",  ThirdForm=  "fled",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Fling,new Word   {   RussianName=    "Кидать",  FirstForm=  "fling",  SecondForm= "flung",  ThirdForm=  "flung",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Fly , new Word   {   RussianName=    "Летать",  FirstForm=  "fly",  SecondForm= "flew",  ThirdForm=  "flown",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Forbid, new Word   {   RussianName=    "Запрещать",  FirstForm=  "forbid",  SecondForm= "forbade",  ThirdForm=  "forbidden",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Forecast, new Word   {   RussianName=    "Предвидеть",  FirstForm=  "forecast",  SecondForm= "forecast",  ThirdForm=  "forecast",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Forget, new Word   {   RussianName=    "Забывать",  FirstForm=  "forget",  SecondForm= "forgot",  ThirdForm=  "forgotten",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Forego, new Word   {   RussianName=    "Отказываться",  FirstForm=  "forego",  SecondForm= "forewent",  ThirdForm=  "foregone",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Foretell, new Word   {   RussianName=    "Предсказывать",  FirstForm=  "foretell",  SecondForm= "foretold",  ThirdForm=  "foretold",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Forgive , new Word   {   RussianName=    "Прощать",  FirstForm=  "forgive",  SecondForm= "forgave",  ThirdForm=  "forgiven",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Forsake , new Word   {   RussianName=    "Бросать",  FirstForm=  "forsake",  SecondForm= "forsook",  ThirdForm=  "forsaken",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Freeze, new Word   {   RussianName=    "Замерзать",  FirstForm=  "freeze",  SecondForm= "froze",  ThirdForm=  "frozen",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Get , new Word   {   RussianName=    "Получать",  FirstForm=  "get",  SecondForm= "got",  ThirdForm=  "got",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Gild, new Word   {   RussianName=    "Позолотить",  FirstForm=  "gild",  SecondForm= "gilt",  ThirdForm=  "gilt",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Give, new Word   {   RussianName=    "Давать",  FirstForm=  "give",  SecondForm= "gave",  ThirdForm=  "given",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Go , new Word   {   RussianName=    "Идти",  FirstForm=  "go/goes",  SecondForm= "went",  ThirdForm=  "gone",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Grind,new Word   {   RussianName=    "Точить",  FirstForm=  "grind",  SecondForm= "ground",  ThirdForm=  "ground",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Grow, new Word   {   RussianName=    "Расти",  FirstForm=  "grow",  SecondForm= "grew",  ThirdForm=  "grown",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Hang, new Word   {   RussianName=    "Висеть",  FirstForm=  "hang",  SecondForm= "hung",  ThirdForm=  "hung",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Have, new Word   {   RussianName=    "Иметь",  FirstForm=  "have",  SecondForm= "had",  ThirdForm=  "had",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Hew , new Word   {   RussianName=    "Рубить",  FirstForm=  "hew",  SecondForm= "hewed",  ThirdForm=  "hewed",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Hear, new Word   {   RussianName=    "Слышать",  FirstForm=  "hear",  SecondForm= "heard",  ThirdForm=  "heard",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Hide, new Word   {   RussianName=    "Прятать",  FirstForm=  "hide",  SecondForm= "hid",  ThirdForm=  "hidden",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Hit , new Word   {   RussianName=    "Ударять",  FirstForm=  "hit",  SecondForm= "hit",  ThirdForm=  "hit",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Hold, new Word   {   RussianName=    "Держать",  FirstForm=  "hold",  SecondForm= "held",  ThirdForm=  "held",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Hurt, new Word   {   RussianName=    "Повредить",  FirstForm=  "hurt",  SecondForm= "hurt",  ThirdForm=  "hurt",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Keep, new Word   {   RussianName=    "Держать",  FirstForm=  "keep",  SecondForm= "kept",  ThirdForm=  "kept",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Kneel,new Word   {   RussianName=    "Становиться На Колени",  FirstForm=  "kneel",  SecondForm= "knelt",  ThirdForm=  "knelt",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Knit, new Word   {   RussianName=    "Вязать",  FirstForm=  "knit",  SecondForm= "knit",  ThirdForm=  "knit",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Know, new Word   {   RussianName=    "Знать",  FirstForm=  "know",  SecondForm= "knew",  ThirdForm=  "known",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Lay , new Word   {   RussianName=    "Класть",  FirstForm=  "lay",  SecondForm= "laid",  ThirdForm=  "laid",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Lead, new Word   {   RussianName=    "Вести",  FirstForm=  "lead",  SecondForm= "led",  ThirdForm=  "led",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Lean, new Word   {   RussianName=    "Опираться",  FirstForm=  "lean",  SecondForm= "leant",  ThirdForm=  "leant",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Leap, new Word   {   RussianName=    "Прыгать",  FirstForm=  "leap",  SecondForm= "leapt",  ThirdForm=  "leapt",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Learn,new Word   {   RussianName=    "Учиться",  FirstForm=  "learn",  SecondForm= "learnt",  ThirdForm=  "learnt",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Leave,new Word   {   RussianName=    "Оставлять",  FirstForm=  "leave",  SecondForm= "left",  ThirdForm=  "left",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Lend, new Word   {   RussianName=    "Одалживать",  FirstForm=  "lend",  SecondForm= "lent",  ThirdForm=  "lent",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Let , new Word   {   RussianName=    "Позволять",  FirstForm=  "let",  SecondForm= "let",  ThirdForm=  "let",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Lie , new Word   {   RussianName=    "Лежать",  FirstForm=  "lie",  SecondForm= "lay",  ThirdForm=  "lain",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Light,new Word   {   RussianName=    "Зажигать",  FirstForm=  "light",  SecondForm= "lit",  ThirdForm=  "lit",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Lose, new Word   {   RussianName=    "Терять",  FirstForm=  "lose",  SecondForm= "lost",  ThirdForm=  "lost",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Make, new Word   {   RussianName=    "Делать",  FirstForm=  "make",  SecondForm= "made",  ThirdForm=  "made",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.May , new Word   {   RussianName=    "Мочь",  FirstForm=  "may",  SecondForm= "might",  ThirdForm=  "might",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Mean, new Word   {   RussianName=    "Значить",  FirstForm=  "mean",  SecondForm= "meant",  ThirdForm=  "meant",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Meet, new Word   {   RussianName=    "Встречать",  FirstForm=  "meet",  SecondForm= "met",  ThirdForm=  "met",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Mishear , new Word   {   RussianName=    "Ослышаться",  FirstForm=  "mishear",  SecondForm= "misheard",  ThirdForm=  "misheard",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Mislay, new Word   {   RussianName=    "Класть Не На Место",  FirstForm=  "mislay",  SecondForm= "mislaid",  ThirdForm=  "mislaid",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Mistake , new Word   {   RussianName=    "Ошибаться",  FirstForm=  "mistake",  SecondForm= "mistook",  ThirdForm=  "mistaken",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Mow , new Word   {   RussianName=    "Косить",  FirstForm=  "mow",  SecondForm= "mowed",  ThirdForm=  "mown",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Overtake, new Word   {   RussianName=    "Догнать",  FirstForm=  "overtake",  SecondForm= "overtook",  ThirdForm=  "overtaken",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Pay , new Word   {   RussianName=    "Платить",  FirstForm=  "pay",  SecondForm= "paid",  ThirdForm=  "paid",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Prove,new Word   {   RussianName=    "Доказывать",  FirstForm=  "prove",  SecondForm= "proved",  ThirdForm=  "proved; proven",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Put , new Word   {   RussianName=    "Класть",  FirstForm=  "put",  SecondForm= "put",  ThirdForm=  "put",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Quit, new Word   {   RussianName=    "Оставлять",  FirstForm=  "quit",  SecondForm= "quit; quitted",  ThirdForm=  "quit; quitted",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Read, new Word   {   RussianName=    "Читать",  FirstForm=  "read",  SecondForm= "read; red",  ThirdForm=  "read; red",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Rebuild , new Word   {   RussianName=    "Перестраивать",  FirstForm=  "rebuild",  SecondForm= "rebuilt",  ThirdForm=  "rebuilt",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Rid , new Word   {   RussianName=    "Освобождать",  FirstForm=  "rid",  SecondForm= "rid; ridded",  ThirdForm=  "rid; ridded",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Ride, new Word   {   RussianName=    "Ехать Верхом",  FirstForm=  "ride",  SecondForm= "rode",  ThirdForm=  "ridden",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Ring, new Word   {   RussianName=    "Звонить",  FirstForm=  "ring",  SecondForm= "rang",  ThirdForm=  "rung",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Rise, new Word   {   RussianName=    "Подниматься",  FirstForm=  "rise",  SecondForm= "rose",  ThirdForm=  "risen",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Run , new Word   {   RussianName=    "Бежать",  FirstForm=  "run",  SecondForm= "ran",  ThirdForm=  "run",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Saw , new Word   {   RussianName=    "Пилить",  FirstForm=  "saw",  SecondForm= "sawed",  ThirdForm=  "sawn; sawed",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Say , new Word   {   RussianName=    "Говорить",  FirstForm=  "say",  SecondForm= "said",  ThirdForm=  "said",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.See , new Word   {   RussianName=    "Видеть",  FirstForm=  "see",  SecondForm= "saw",  ThirdForm=  "seen",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Seek, new Word   {   RussianName=    "Искать",  FirstForm=  "seek",  SecondForm= "sought",  ThirdForm=  "sought",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Sell, new Word   {   RussianName=    "Продавать",  FirstForm=  "sell",  SecondForm= "sold",  ThirdForm=  "sold",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Send, new Word   {   RussianName=    "Посылать",  FirstForm=  "send",  SecondForm= "sent",  ThirdForm=  "sent",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Set , new Word   {   RussianName=    "Помещать",  FirstForm=  "set",  SecondForm= "set",  ThirdForm=  "set",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Sew , new Word   {   RussianName=    "Шить",  FirstForm=  "sew",  SecondForm= "sewed",  ThirdForm=  "sewed; sewn",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Shake,new Word   {   RussianName=    "Трясти",  FirstForm=  "shake",  SecondForm= "shook",  ThirdForm=  "shaken",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Shall,new Word   {   RussianName=    "Быть Должным",  FirstForm=  "shall",  SecondForm= "should",  ThirdForm=  "should",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Shave,new Word   {   RussianName=    "Брить",  FirstForm=  "shave",  SecondForm= "shaved",  ThirdForm=  "shaved",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Shear,new Word   {   RussianName=    "Стричь",  FirstForm=  "shear",  SecondForm= "sheared",  ThirdForm=  "shorn",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Shed, new Word   {   RussianName=    "Сбрасывать",  FirstForm=  "shed",  SecondForm= "shed",  ThirdForm=  "shed",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Shine,new Word   {   RussianName=    "Сиять",  FirstForm=  "shine",  SecondForm= "shone; shined",  ThirdForm=  "shone; shined",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Shoe, new Word   {   RussianName=    "Обувать",  FirstForm=  "shoe",  SecondForm= "shod",  ThirdForm=  "shod",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Shoot,new Word   {   RussianName=    "Стрелять",  FirstForm=  "shoot",  SecondForm= "shot",  ThirdForm=  "shot",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Show, new Word   {   RussianName=    "Показывать",  FirstForm=  "show",  SecondForm= "showed",  ThirdForm=  "shown; showed",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Shrink, new Word   {   RussianName=    "Сокращаться",  FirstForm=  "shrink",  SecondForm= "shrank; shrunk",  ThirdForm=  "shrunk",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Shut, new Word   {   RussianName=    "Закрывать",  FirstForm=  "shut",  SecondForm= "shut",  ThirdForm=  "shut",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Sing, new Word   {   RussianName=    "Петь",  FirstForm=  "sing",  SecondForm= "sang",  ThirdForm=  "sung",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Sink, new Word   {   RussianName=    "Опускаться",  FirstForm=  "sink",  SecondForm= "sank",  ThirdForm=  "sunk",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Sit , new Word   {   RussianName=    "Сидеть",  FirstForm=  "sit",  SecondForm= "sat",  ThirdForm=  "sat",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Slay, new Word   {   RussianName=    "Убивать",  FirstForm=  "slay",  SecondForm= "slew",  ThirdForm=  "slain",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Sleep,new Word   {   RussianName=    "Спать",  FirstForm=  "sleep",  SecondForm= "slept",  ThirdForm=  "slept",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Slide,new Word   {   RussianName=    "Скользить",  FirstForm=  "slide",  SecondForm= "slid",  ThirdForm=  "slid",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Sling,new Word   {   RussianName=    "Швырять",  FirstForm=  "sling",  SecondForm= "slung",  ThirdForm=  "slung",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Slit, new Word   {   RussianName=    "Резать В Длину",  FirstForm=  "slit",  SecondForm= "slit",  ThirdForm=  "slit",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Smell,new Word   {   RussianName=    "Пахнуть",  FirstForm=  "smell",  SecondForm= "smelt; smelled",  ThirdForm=  "smelt; smelled",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Sow , new Word   {   RussianName=    "Сеять",  FirstForm=  "sow",  SecondForm= "sowed",  ThirdForm=  "sowed; sown",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Speak,new Word   {   RussianName=    "Говорить",  FirstForm=  "speak",  SecondForm= "spoke",  ThirdForm=  "spoken",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Speed,new Word   {   RussianName=    "Спешить",  FirstForm=  "speed",  SecondForm= "sped; speeded",  ThirdForm=  "sped; speeded",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Spell,new Word   {   RussianName=    "Писать",  FirstForm=  "spell",  SecondForm= "spelt; spelled",  ThirdForm=  "spelt; spelled",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Spend,new Word   {   RussianName=    "Тратить",  FirstForm=  "spend",  SecondForm= "spent",  ThirdForm=  "spent",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Spill,new Word   {   RussianName=    "Проливать",  FirstForm=  "spill",  SecondForm= "spilt",  ThirdForm=  "spilt",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Spin, new Word   {   RussianName=    "Прясть",  FirstForm=  "spin",  SecondForm= "spun",  ThirdForm=  "spun",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Spit, new Word   {   RussianName=    "Плевать",  FirstForm=  "spit",  SecondForm= "spat",  ThirdForm=  "spat",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Split,new Word   {   RussianName=    "Раскалывать",  FirstForm=  "split",  SecondForm= "split",  ThirdForm=  "split",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Spoil,new Word   {   RussianName=    "Портить",  FirstForm=  "spoil",  SecondForm= "spoilt; spoiled",  ThirdForm=  "spoilt; spoiled",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Spread, new Word   {   RussianName=    "Распространяться",  FirstForm=  "spread",  SecondForm= "spread",  ThirdForm=  "spread",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Spring, new Word   {   RussianName=    "Прыгать",  FirstForm=  "spring",  SecondForm= "sprang",  ThirdForm=  "sprung",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Stand,new Word   {   RussianName=    "Стоять",  FirstForm=  "stand",  SecondForm= "stood",  ThirdForm=  "stood",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Steal,new Word   {   RussianName=    "Воровать",  FirstForm=  "steal",  SecondForm= "stole",  ThirdForm=  "stolen",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Stick,new Word   {   RussianName=    "Втыкать",  FirstForm=  "stick",  SecondForm= "stuck",  ThirdForm=  "stuck",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Sting,new Word   {   RussianName=    "Жалить",  FirstForm=  "sting",  SecondForm= "stung",  ThirdForm=  "stung",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Stink,new Word   {   RussianName=    "Вонять",  FirstForm=  "stink",  SecondForm= "stank; stunk",  ThirdForm=  "stunk",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Strew,new Word   {   RussianName=    "Усеять",  FirstForm=  "strew",  SecondForm= "strewed",  ThirdForm=  "strewn; strewed",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Stride, new Word   {   RussianName=    "Шагать",  FirstForm=  "stride",  SecondForm= "strode",  ThirdForm=  "stridden",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Strike, new Word   {   RussianName=    "Ударять",  FirstForm=  "strike",  SecondForm= "struck",  ThirdForm=  "struck",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.String, new Word   {   RussianName=    "Связывать",  FirstForm=  "string",  SecondForm= "strung",  ThirdForm=  "strung",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Strive, new Word   {   RussianName=    "Стремиться",  FirstForm=  "strive",  SecondForm= "strove",  ThirdForm=  "striven",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Swear,new Word   {   RussianName=    "Клясться",  FirstForm=  "swear",  SecondForm= "swore",  ThirdForm=  "sworn",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Sweep,new Word   {   RussianName=    "Мести",  FirstForm=  "sweep",  SecondForm= "swept",  ThirdForm=  "swept",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Swell,new Word   {   RussianName=    "Пухнуть",  FirstForm=  "swell",  SecondForm= "swelled",  ThirdForm=  "swollen; swelled",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Swim, new Word   {   RussianName=    "Плавать",  FirstForm=  "swim",  SecondForm= "swam",  ThirdForm=  "swum",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Swing,new Word   {   RussianName=    "Качать",  FirstForm=  "swing",  SecondForm= "swung",  ThirdForm=  "swung",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Take, new Word   {   RussianName=    "Брать",  FirstForm=  "take",  SecondForm= "took",  ThirdForm=  "taken",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Teach,new Word   {   RussianName=    "Обучать",  FirstForm=  "teach",  SecondForm= "taught",  ThirdForm=  "taught",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Tear, new Word   {   RussianName=    "Рвать",  FirstForm=  "tear",  SecondForm= "tore",  ThirdForm=  "torn",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Tell, new Word   {   RussianName=    "Рассказывать",  FirstForm=  "tell",  SecondForm= "told",  ThirdForm=  "told",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Think,new Word   {   RussianName=    "Думать",  FirstForm=  "think",  SecondForm= "thought",  ThirdForm=  "thought",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Throw,new Word   {   RussianName=    "Кидать",  FirstForm=  "throw",  SecondForm= "threw",  ThirdForm=  "thrown",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Thrust, new Word   {   RussianName=    "Толкать",  FirstForm=  "thrust",  SecondForm= "thrust",  ThirdForm=  "thrust",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Tread,new Word   {   RussianName=    "Ступать",  FirstForm=  "tread",  SecondForm= "trod",  ThirdForm=  "trod; trodden",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Unbend, new Word   {   RussianName=    "Разгибаться",  FirstForm=  "unbend",  SecondForm= "unbent",  ThirdForm=  "unbent",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Undergo , new Word   {   RussianName=    "Испытывать",  FirstForm=  "undergo",  SecondForm= "underwent",  ThirdForm=  "undergone",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Understand, new Word   {   RussianName=    "Понимать",  FirstForm=  "understand",  SecondForm= "understood",  ThirdForm=  "understood",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Undertake,new Word   {   RussianName=    "Предпринимать",  FirstForm=  "undertake",  SecondForm= "undertook",  ThirdForm=  "undertaken",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Upset,new Word   {   RussianName=    "Опрокидывать",  FirstForm=  "upset",  SecondForm= "upset",  ThirdForm=  "upset",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Wake, new Word   {   RussianName=    "Будить",  FirstForm=  "wake",  SecondForm= "woke; waked",  ThirdForm=  "woken; waked",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Wear, new Word   {   RussianName=    "Носить",  FirstForm=  "wear",  SecondForm= "wore",  ThirdForm=  "worn",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Weave,new Word   {   RussianName=    "Ткать",  FirstForm=  "weave",  SecondForm= "wove; weaved",  ThirdForm=  "woven; weaved",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Wed , new Word   {   RussianName=    "Венчать",  FirstForm=  "wed",  SecondForm= "wed; wedded",  ThirdForm=  "wed; wedded",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Weep, new Word   {   RussianName=    "Плакать",  FirstForm=  "weep",  SecondForm= "wept",  ThirdForm=  "wept",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Will, new Word   {   RussianName=    "Хотеть Быть",  FirstForm=  "will",  SecondForm= "would",  ThirdForm=  "would",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Wet , new Word   {   RussianName=    "Мочить",  FirstForm=  "wet",  SecondForm= "wet; wetted",  ThirdForm=  "wet; wetted",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Win , new Word   {   RussianName=    "Выигрывать",  FirstForm=  "win",  SecondForm= "won",  ThirdForm=  "won",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}  }   },
         {   Words.Wind, new Word   {   RussianName=    "Заводить",  FirstForm=  "wind",  SecondForm= "wound",  ThirdForm=  "wound",  SentencesWithWordList =new List<string> {   "📌1111",  "📌2222",  "📌3333"}   }   },
         {   Words.Withdraw, new Word   {   RussianName=    "Брать Назад",  FirstForm=  "withdraw",  SecondForm= "withdrew",  ThirdForm=  "withdrawn",  SentencesWithWordList =new List<string> { "📌1111", "📌2222", "📌3333" }  }   },
         {   Words.Wring,new Word   {   RussianName=    "Жать",  FirstForm=  "wring",  SecondForm= "wrung",  ThirdForm=  "wrung",  SentencesWithWordList =new List<string> { "📌1111", "📌2222", "📌3333" }  }   },
         {   Words.Write,new Word   {   RussianName=    "Писать",  FirstForm=  "write",  SecondForm= "wrote",  ThirdForm=  "written",  SentencesWithWordList =new List<string> { "📌1111", "📌2222", "📌3333" }  }   }

        };
    }
}